<a href="https://colab.research.google.com/github/faizahm-gif/iiit-h_AIML-TrainingProgram/blob/main/Pandas_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
sample_songs = [
    ["time flies","Toosie SLide", "Pain 1993" ],
    ["Virginia Beach", "Honestly Never mind","Jimmy Cooks"],
    ["9","One Dance","Hotline Bling"]
]
#using lists

In [3]:
pd.DataFrame(sample_songs,columns=["DLDT","Honestly Never Mind","Views"])

             DLDT  Honestly Never Mind          Views
0      time flies         Toosie SLide      Pain 1993
1  Virginia Beach  Honestly Never mind    Jimmy Cooks
2               9            One Dance  Hotline Bling

In [4]:
artists_dict={
    'DLDT':['Toosie Slide'],
    'Honestly Never Mind':['Jimmy Cooks'],
    'Views':['Hotline Bling']
}

In [5]:
art=pd.DataFrame(artists_dict)
art.set_index('DLDT',inplace=True)
print(art)

             Honestly Never Mind          Views
DLDT
Toosie Slide         Jimmy Cooks  Hotline Bling

In [6]:
spotify = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/Spotify_Music.csv')

In [7]:
print(spotify)

        Unnamed: 0                track_id                 artists  \
0                0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino
1                1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward
2                2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN
3                3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis
4                4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet
...            ...                     ...                     ...
113995      113995  2C3TZjDRiAzdyViavDJ217           Rainy Lullaby
113996      113996  1hIz5L4IB9hN3WRYPOCGPw           Rainy Lullaby
113997      113997  6x8ZfSoqDjuNa5SVP5QjvX           Cesária Evora
113998      113998  2e6sXL2bYv4bSz6VTdnfLs        Michael W. Smith
113999      113999  2hETkH7cOfqmz3LqZDHZf5           Cesária Evora

                                               album_name  \
0                                                  Comedy
1                                        Ghost (Acoustic)
2                                          To Begin Again
3       Crazy Rich Asians (Original Motion Picture Sou...
4                                                 Hold On
...                                                   ...
113995  #mindfulness - Soft Rain for Mindful Meditatio...
113996  #mindfulness - Soft Rain for Mindful Meditatio...
113997                                            Best Of
113998                                  Change Your World
113999                                     Miss Perfumado

                        track_name  popularity  duration_ms  explicit  \
0                           Comedy          73       230666     False
1                 Ghost - Acoustic          55       149610     False
2                   To Begin Again          57       210826     False
3       Can't Help Falling In Love          71       201933     False
4                          Hold On          82       198853     False
...                            ...         ...          ...       ...
113995         Sleep My Little Boy          21       384999     False
113996            Water Into Light          22       385000     False
113997              Miss Perfumado          22       271466     False
113998                     Friends          41       283893     False
113999                   Barbincor          22       241826     False

        danceability  energy  ...  loudness  mode  speechiness  acousticness  \
0              0.676  0.4610  ...    -6.746     0       0.1430        0.0322
1              0.420  0.1660  ...   -17.235     1       0.0763        0.9240
2              0.438  0.3590  ...    -9.734     1       0.0557        0.2100
3              0.266  0.0596  ...   -18.515     1       0.0363        0.9050
4              0.618  0.4430  ...    -9.681     1       0.0526        0.4690
...              ...     ...  ...       ...   ...          ...           ...
113995         0.172  0.2350  ...   -16.393     1       0.0422        0.6400
113996         0.174  0.1170  ...   -18.318     0       0.0401        0.9940
113997         0.629  0.3290  ...   -10.895     0       0.0420        0.8670
113998         0.587  0.5060  ...   -10.889     1       0.0297        0.3810
113999         0.526  0.4870  ...   -10.204     0       0.0725        0.6810

        instrumentalness  liveness  valence    tempo  time_signature  \
0               0.000001    0.3580   0.7150   87.917               4
1               0.000006    0.1010   0.2670   77.489               4
2               0.000000    0.1170   0.1200   76.332               4
3               0.000071    0.1320   0.1430  181.740               3
4               0.000000    0.0829   0.1670  119.949               4
...                  ...       ...      ...      ...             ...
113995          0.928000    0.0863   0.0339  125.995               5
113996          0.976000    0.1050   0.0350   85.239               4
113997          0.000000    0.0839   0.7430  132.378               4
113998          0.000000    0.2700   0.4130  135.960               4
113999          0.000000    0.0893   0.7080   79.198               4

        track_genre
0          acoustic
1          acoustic
2          acoustic
3          acoustic
4          acoustic
...             ...
113995  world-music
113996  world-music
113997  world-music
113998  world-music
113999  world-music

[114000 rows x 21 columns]

<h1> Attributes and Methods

In [8]:
spotify.shape #give the number of rows and columns

(114000, 21)

In [9]:
spotify.dtypes #gives the data type of each and every column

Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [10]:
spotify.index #gives the indexes

RangeIndex(start=0, stop=114000, step=1)

In [11]:
spotify.columns #gives names all columns in the dataset

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [12]:
spotify.values #gives values present in all rows

array([[0, '5SuOikwiRyPMVoIQDJUgSV', 'Gen Hoshino', ..., 87.917, 4,
        'acoustic'],
       [1, '4qPNDBW1i3p13qLCt0Ki3A', 'Ben Woodward', ..., 77.489, 4,
        'acoustic'],
       [2, '1iJBSr7s7jYXzM8EGcbK5b', 'Ingrid Michaelson;ZAYN', ...,
        76.332, 4, 'acoustic'],
       ...,
       [113997, '6x8ZfSoqDjuNa5SVP5QjvX', 'Cesária Evora', ..., 132.378,
        4, 'world-music'],
       [113998, '2e6sXL2bYv4bSz6VTdnfLs', 'Michael W. Smith', ...,
        135.96, 4, 'world-music'],
       [113999, '2hETkH7cOfqmz3LqZDHZf5', 'Cesária Evora', ..., 79.198,
        4, 'world-music']], dtype=object)

In [13]:
spotify.head(2) #gives top 2 values present in the dataset

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.461,...,-6.746,0,0.1430,0.0322,0.000001,0.358,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.166,...,-17.235,1,0.0763,0.9240,0.000006,0.101,0.267,77.489,4,acoustic

In [14]:
spotify.tail(2) #gives bottom 2 values present in the dataset

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.381,0.0,0.2700,0.413,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.681,0.0,0.0893,0.708,79.198,4,world-music

In [15]:
spotify.sample(10) #gives 10 random values

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
7691,7691,3GmgxjJpkSamedNinjO3rB,The Carter Family;Johnny Cash,Keep On The Sunny Side,Keep on the Sunny Side,25,147173,False,0.574,0.3240,...,-11.060,1,0.0265,0.768000,0.000000,0.1410,0.6270,101.176,4,bluegrass
1348,1348,54sxsI1fcUJSAmKyty00r5,Mandrill,Le monde de demain (Bande originale de la série),Can You Get It,7,427160,False,0.858,0.9120,...,-8.237,1,0.0622,0.173000,0.025400,0.0448,0.7980,122.496,4,afrobeat
21615,21615,7EEinxDxDsRX3AIIJ026TZ,Omah Lay,Boy Alone,safe haven,49,169031,False,0.678,0.4690,...,-6.422,0,0.0289,0.488000,0.099600,0.1080,0.2070,107.961,4,dancehall
12777,12777,63huDpEdqQBN43UgxhoIcX,Hins Cheung,酷愛,酷愛,49,234360,False,0.744,0.7130,...,-6.178,0,0.0471,0.126000,0.000000,0.1540,0.5210,139.979,4,cantopop
101000,101000,07UDTaRYJAsIhUZTyZSUzM,Huma,Ons,Ons,71,193239,False,0.111,0.0185,...,-32.335,1,0.0424,0.957000,0.940000,0.0870,0.0459,76.153,3,sleep
53600,53600,1vvNmPOiUuyCbgWmtc6yfm,Calvin Harris,My Way,My Way,76,219159,False,0.818,0.9130,...,-3.060,0,0.0426,0.093000,0.000037,0.1610,0.5360,119.986,4,house
36170,36170,4vC2iSW6pMcDvAb98Tc8ma,Lonely in the Rain;De Rien,Hangin Up,Hangin Up,59,184296,False,0.656,0.5220,...,-10.777,1,0.1100,0.700000,0.005090,0.1120,0.1760,111.824,4,french
77435,77435,5YRbulSfqr7x2pYsY3CKjc,Belo,Belo Ao Vivo,Antes De Dizer Adeus / Farol De Estrelas - Liv...,45,300200,False,0.323,0.6290,...,-9.252,1,0.0398,0.662000,0.000000,0.9570,0.5590,141.444,4,pagode
35668,35668,0ljOkdY8AKoNgd6xo5TyZR,Unha Pintada,Ao Vivo em Salvador Bahia,Meu Deus,39,206680,False,0.740,0.6320,...,-5.637,1,0.0334,0.421000,0.000000,0.6570,0.6970,137.011,4,forro
44208,44208,4QJLKU75Rg4558f4LbDBRi,Nickelback,Dark Horse,If Today Was Your Last Day,68,249066,False,0.485,0.9110,...,-5.749,1,0.0355,0.000087,0.000000,0.0920,0.5680,89.956,4,grunge

In [16]:
spotify.info() #gives complete information about the dataset, it gives number of non null values per column,gives the datatype of a column, and total memory usage etc....

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [17]:
spotify.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [18]:
spotify.isnull()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
spotify.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [20]:
spotify.duplicated().sum()

np.int64(0)

In [21]:
spotify.rename(columns={'track_id':'unique_id'},inplace=True)

<h1> Mathematical Functions with Data Frame

In [22]:
#.sum()
#.var()
#.mean()
#.median()
#.std() etc.....
spotify['popularity'].var()

497.5165265953142

Selecting Columns from Data Frame

In [23]:
spotify['track_name']

0                             Comedy
1                   Ghost - Acoustic
2                     To Begin Again
3         Can't Help Falling In Love
4                            Hold On
                     ...
113995           Sleep My Little Boy
113996              Water Into Light
113997                Miss Perfumado
113998                       Friends
113999                     Barbincor
Name: track_name, Length: 114000, dtype: object

In [24]:
type(spotify['track_name'])

pandas.core.series.Series

In [25]:
spotify[['track_name','album_name','artists']]

,track_name,album_name,artists
0,Comedy,Comedy,Gen Hoshino
1,Ghost - Acoustic,Ghost (Acoustic),Ben Woodward
2,To Begin Again,To Begin Again,Ingrid Michaelson;ZAYN
3,Can't Help Falling In Love,Crazy Rich Asians (Original Motion Picture Sou...,Kina Grannis
4,Hold On,Hold On,Chord Overstreet
...,...,...,...
113995,Sleep My Little Boy,#mindfulness - Soft Rain for Mindful Meditatio...,Rainy Lullaby
113996,Water Into Light,#mindfulness - Soft Rain for Mindful Meditatio...,Rainy Lullaby
113997,Miss Perfumado,Best Of,Cesária Evora
113998,Friends,Change Your World,Michael W. Smith
113999,Barbincor,Miss Perfumado,Cesária Evora

In [26]:
type(spotify[['track_name','album_name','artists']])

pandas.core.frame.DataFrame

Selecting Rows from the Data

In [27]:
spotify.iloc[0] #selecting single row

Unnamed: 0                               0
unique_id           5SuOikwiRyPMVoIQDJUgSV
artists                        Gen Hoshino
album_name                          Comedy
track_name                          Comedy
popularity                              73
duration_ms                         230666
explicit                             False
danceability                         0.676
energy                               0.461
key                                      1
loudness                            -6.746
mode                                     0
speechiness                          0.143
acousticness                        0.0322
instrumentalness                  0.000001
liveness                             0.358
valence                              0.715
tempo                               87.917
time_signature                           4
track_genre                       acoustic
Name: 0, dtype: object

In [28]:
spotify.iloc[[0,3,4]] #selecting multiple rows

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [29]:
spotify.loc[1:4] #gives a range of values from 1 to 4; but here last value is also included unlike indexing in lists

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.924,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.210,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.905,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.469,0.000000,0.0829,0.167,119.949,4,acoustic

** Difference between loc and iloc:
In loc you select rows based on label indexing where as in iloc you select based on integer indexing
**

<h1> Filtering a Dataframe

In [30]:
spotify

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

Here we get a boolean series whenever we check the condition; now when we insert that series in the database, it will display all the rows where it is 'true' i.e. where the condition satisfies.

In [31]:
spotify['artists']=='Kendrick Lamar'

0         False
1         False
2         False
3         False
4         False
          ...
113995    False
113996    False
113997    False
113998    False
113999    False
Name: artists, Length: 114000, dtype: bool

In [32]:
spotify[spotify['artists']=='Kendrick Lamar']

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
51500,51500,7KXjTSCq5nL1LoYtL7XAwS,Kendrick Lamar,DAMN.,HUMBLE.,84,177000,True,0.908,0.621,...,-6.638,0,0.102,0.000282,0.000054,0.0958,0.421,150.011,4,hip-hop
51650,51650,0fX4oNGBWO3dSGUZcVdVV2,Kendrick Lamar,Mr. Morale & The Big Steppers,N95,83,195950,True,0.790,0.670,...,-5.527,1,0.105,0.377000,0.000002,0.1190,0.408,139.956,4,hip-hop

We use the shape[0] to get the number of rows

In [33]:
spotify[spotify['artists']=='Kendrick Lamar'].shape[0]

2

In [34]:
spotify[spotify['artists']=='Drake']

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
51250,51250,6DCZcSspjsKoFjzjrWoCdn,Drake,Scorpion,God's Plan,84,198973,True,0.754,0.449,...,-9.211,1,0.109,0.0332,0.000083,0.552,0.357,77.169,4,hip-hop

In [35]:
spotify[spotify['artists']=='Arijit Singh'].shape[0]

52

To filter rows which satisfies two or more conditions in the database then we use '&' (bitwise and) because the values which we are comparing are 'True' or 'False' i.e. 1 or 0.

In [36]:
spotify[(spotify['track_genre']=='hip-hop') & (spotify['artists']=='AP Dhillon')]

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
51000,51000,1aL9518P5G72N92b48tuKw,AP Dhillon,Summer High,Summer High,83,177391,False,0.860,0.541,...,-6.510,0,0.0325,0.165,0.163000,0.0663,0.952,114.984,4,hip-hop
51009,51009,32FVH23yFXr8Z0sfjRw4It,AP Dhillon,Two Hearts Never Break The Same,Wo Noor,72,199420,False,0.761,0.554,...,-8.119,0,0.0854,0.193,0.008440,0.0802,0.555,92.520,4,hip-hop
51054,51054,3iICKiDTyIK5qoVl2hXB2f,AP Dhillon,Two Hearts Never Break The Same,Summer High,63,177391,False,0.860,0.541,...,-6.510,0,0.0325,0.165,0.163000,0.0663,0.952,114.984,4,hip-hop
51063,51063,6SPLYHHBN0dKGaoD2Jcccs,AP Dhillon,Two Hearts Never Break The Same,Hills,68,159942,False,0.779,0.331,...,-10.115,1,0.0794,0.411,0.005770,0.1100,0.182,96.012,4,hip-hop
51360,51360,2N0oWy78RT70bW10QfIVHT,AP Dhillon,Top Boy,Top Boy,63,136941,False,0.804,0.609,...,-8.481,0,0.2680,0.375,0.000002,0.1090,0.652,169.819,4,hip-hop

In [37]:
spotify[(spotify['track_genre']=='hip-hop') & (spotify['popularity']>80)]

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
51000,51000,1aL9518P5G72N92b48tuKw,AP Dhillon,Summer High,Summer High,83,177391,False,0.860,0.541,...,-6.510,0,0.0325,0.165000,0.163000,0.0663,0.9520,114.984,4,hip-hop
51001,51001,08Isz2ETWSBhvIl8UpKYsp,Shubh,No Love,No Love,83,170387,False,0.768,0.487,...,-8.936,0,0.0431,0.240000,0.000000,0.1750,0.7220,137.034,4,hip-hop
51002,51002,42TMa2hgBNjte4uV7jNCnQ,Shubh;Ikky,Baller,Baller,82,148188,False,0.711,0.702,...,-10.048,1,0.2330,0.004870,0.016300,0.0932,0.6740,180.219,4,hip-hop
51004,51004,5HCyWlXZPP0y6Gqq8TgA20,The Kid LAROI;Justin Bieber,STAY (with Justin Bieber),STAY (with Justin Bieber),89,141805,True,0.591,0.764,...,-5.484,1,0.0483,0.038300,0.000000,0.1030,0.4780,169.928,4,hip-hop
51010,51010,29m79w9xPMH4YCD6r8JSmV,AP Dhillon;Gurinder Gill;Intense,Excuses,Excuses,82,176232,False,0.837,0.717,...,-7.749,0,0.0822,0.084200,0.000000,0.1490,0.4940,94.984,4,hip-hop
51015,51015,2ZRo7axmMPeSVUvDbGkJah,XXXTENTACION,?,Hope,86,110886,True,0.592,0.457,...,-6.081,0,0.0603,0.661000,0.000331,0.1460,0.2250,146.040,4,hip-hop
51022,51022,0yCWDaAgOtg6TKlNCg9rwA,King,The Carnival,Tu Aake Dekhle,81,270000,False,0.770,0.840,...,-4.022,1,0.1070,0.515000,0.004520,0.1450,0.1920,96.012,4,hip-hop
51050,51050,27NovPIUIRrOZoCHxABJwK,Lil Nas X;Jack Harlow,INDUSTRY BABY (feat. Jack Harlow),INDUSTRY BABY (feat. Jack Harlow),86,212000,True,0.736,0.704,...,-7.409,0,0.0615,0.020300,0.000000,0.0501,0.8940,149.995,4,hip-hop
51051,51051,0e8nrvls4Qqv5Rfa2UhqmO,Lil Nas X,MONTERO,THATS WHAT I WANT,87,143901,True,0.737,0.846,...,-4.510,0,0.2200,0.006140,0.000000,0.0486,0.5460,87.981,4,hip-hop
51059,51059,3GVkPk8mqxz0itaAriG1L7,XXXTENTACION,17,Everybody Dies In Their Nightmares,85,95466,True,0.734,0.570,...,-7.066,0,0.1330,0.847000,0.000021,0.1120,0.6890,129.953,4,hip-hop
51060,51060,27ZZdyTSQWI7Cug2d2PkqV,Armani White,BILLIE EILISH.,BILLIE EILISH.,89,99282,True,0.900,0.509,...,-6.647,1,0.2570,0.115000,0.000002,0.0937,0.7650,100.007,4,hip-hop
51062,51062,2JzZzZUQj3Qff7wapcbKjc,Wiz Khalifa;Charlie Puth,See You Again (feat. Charlie Puth),See You Again (feat. Charlie Puth),82,229525,False,0.689,0.481,...,-7.503,1,0.0815,0.369000,0.000001,0.0649,0.2830,80.025,4,hip-hop
51088,51088,5PjdY0CKGZdEuoNab3yDmX,The Kid LAROI;Justin Bieber,F*CK LOVE 3: OVER YOU,STAY (with Justin Bieber),86,141805,True,0.591,0.764,...,-5.484,1,0.0483,0.038300,0.000000,0.1030,0.4780,169.928,4,hip-hop
51101,51101,1DIXPcTDzTj8ZMHt3PDt8p,Coolio;L.V.,Gangsta's Paradise,Gangsta's Paradise,89,240693,False,0.647,0.514,...,-10.050,1,0.0593,0.065500,0.000000,0.3980,0.3860,79.975,4,hip-hop
51110,51110,3ee8Jmje8o58CHK66QrVC2,XXXTENTACION,?,SAD!,83,166605,True,0.740,0.613,...,-4.880,1,0.1450,0.258000,0.003720,0.1230,0.4730,75.023,4,hip-hop
51128,51128,1SC5rEoYDGUK4NfG82494W,Lil Nas X,MONTERO,MONTERO (Call Me By Your Name),83,137704,True,0.593,0.503,...,-6.725,0,0.2200,0.293000,0.000000,0.4050,0.7100,178.781,4,hip-hop
51150,51150,3B54sVLJ402zGa6Xm4YGNe,French Montana;Swae Lee,Jungle Rules,Unforgettable,82,233901,True,0.726,0.769,...,-5.043,1,0.1230,0.029300,0.010100,0.1040,0.7330,97.985,4,hip-hop
51151,51151,0JP9xo3adEtGSdUEISiszL,XXXTENTACION,?,Moonlight,83,135090,True,0.921,0.537,...,-5.723,0,0.0804,0.556000,0.004040,0.1020,0.7110,128.009,4,hip-hop
51159,51159,7lQ8MOhq6IN2w8EYcFNSUk,Eminem,The Eminem Show,Without Me,88,290320,True,0.908,0.669,...,-2.827,1,0.0738,0.002860,0.000000,0.2370,0.6620,112.238,4,hip-hop
51200,51200,0VgkVdmE4gld66l8iyGjgx,Future,FUTURE,Mask Off,83,204600,True,0.833,0.434,...,-8.795,1,0.4310,0.010200,0.021900,0.1650,0.2810,150.062,4,hip-hop
51201,51201,7m9OqQk4RVRkw9JJdeAw96,XXXTENTACION,17,Jocelyn Flores,84,119133,True,0.872,0.391,...,-9.144,0,0.2420,0.469000,0.000004,0.2970,0.4370,134.021,4,hip-hop
51203,51203,3F5CgOj3wFlRv51JsHbxhe,Drake;21 Savage,"Honestly, Nevermind",Jimmy Cooks (feat. 21 Savage),91,218364,True,0.529,0.673,...,-4.711,1,0.1750,0.000307,0.000002,0.0930,0.3660,165.921,4,hip-hop
51216,51216,3yfqSUWxFvZELEM4PmlwIR,Eminem,The Marshall Mathers LP,The Real Slim Shady,87,284200,True,0.949,0.661,...,-4.244,0,0.0572,0.030200,0.000000,0.0454,0.7600,104.504,4,hip-hop
51250,51250,6DCZcSspjsKoFjzjrWoCdn,Drake,Scorpion,God's Plan,84,198973,True,0.754,0.449,...,-9.211,1,0.1090,0.033200,0.000083,0.5520,0.3570,77.169,4,hip-hop
51253,51253,7floNISpH8VF4z4459Qo18,XXXTENTACION,Look At Me!,Look At Me!,82,126345,True,0.763,0.726,...,-6.405,1,0.2820,0.259000,0.000000,0.0976,0.3490,139.059,4,hip-hop
51259,51259,38T0tPVZHcPZyhtOcCP7pF,Lil Nas X,STAR WALKIN' (League of Legends Worlds Anthem),STAR WALKIN' (League of Legends Worlds Anthem),90,210575,True,0.637,0.715,...,-4.971,0,0.0455,0.148000,0.000000,0.0892,0.3080,141.872,4,hip-hop
51261,51261,7GNRUsU3M4XNDDB9xle5Dz,PSY;SUGA,PSY 9th,That That (prod. & feat. SUGA of BTS),81,174646,False,0.905,0.962,...,-3.197,1,0.0856,0.029900,0.000000,0.0272,0.9060,129.969,4,hip-hop
51269,51269,5Z9KJZvQzH6PFmb8SNkxuk,Lil Nas X;Jack Harlow,MONTERO,INDUSTRY BABY (feat. Jack Harlow),81,212352,True,0.741,0.691,...,-7.395,0,0.0672,0.022100,0.000000,0.0476,0.8920,150.087,4,hip-hop
51277,51277,4xkOaSrkexMciUUogZKVTS,Eminem;Nate Dogg,The Eminem Show,Till I Collapse,86,297786,True,0.548,0.847,...,-3.237,1,0.1860,0.062200,0.000000,0.0816,0.1000,171.447,4,hip-hop
51300,51300,1zi7xx7UVEFkmKfv06H8x0,Drake;Wizkid;Kyla,Views,One Dance,85,173986,False,0.792,0.625,...,-5.609,1,0.0536,0.007760,0.001800,0.3290,0.3700,103.967,4,hip-hop
51301,51301,3UmaczJpikHgJFyBTAJVoz,Eminem;Dido,The Marshall Mathers LP,Stan,85,404106,True,0.780,0.768,...,-4.325,0,0.2380,0.037100,0.000002,0.5180,0.5070,80.063,4,hip-hop
51303,51303,5uEYRdEIh9Bo4fpjDd4Na9,Travis Scott;HVME,Goosebumps (Remix),Goosebumps - Remix,81,162802,True,0.841,0.593,...,-7.846,1,0.0379,0.418000,0.000000,0.1240,0.8080,124.917,4,hip-hop
51320,51320,7FIWs0pqAYbP91WWM0vlTQ,Eminem;Juice WRLD,Music To Be Murdered By,Godzilla (feat. Juice WRLD),83,210800,True,0.808,0.745,...,-5.260,0,0.3420,0.145000,0.000000,0.2920,0.8290,165.995,4,hip-hop
51350,51350,3GCdLUSnKSMJhs4Tj6CV3s,Kendrick Lamar;SZA,Black Panther The Album Music From And Inspire...,All The Stars (with SZA),83,232186,True,0.698,0.633,...,-4.946,1,0.0597,0.060500,0.000194,0.0926,0.5520,96.924,4,hip-hop
51352,51352,1PckUlxKqWQs3RlWXVBLw3,Lizzo,About Damn Time,About Damn Time,89,191822,True,0.836,0.743,...,-6.305,0,0.0656,0.099500,0.000000,0.3350,0.7220,108.966,4,hip-hop
51369,51369,7Ie9W94M7OjPoZVV216Xus,Eminem,Recovery,Not Afraid,81,248133,True,0.855,0.954,...,-1.190,0,0.2640,0.529000,0.000000,0.2050,0.6680,114.635,5,hip-hop
51401,51401,15JINEqzVMv3SvJTAXAKED,Eminem;Rihanna,Recovery,Love The Way You Lie,83,263373,True,0.749,0.925,...,-5.034,1,0.2270,0.241000,0.000000,0.5200,0.6410,86.989,4,hip-hop
51402,51402,4cacyP5c3PMlfnyjpg13xW,Yung Gravy,Betty (Get Money),Betty (Get Money),87,146470,False,0.723,0.772,...,-6.784,1,0.0792,0.005240,0.000012,0.3670,0.5800,102.004,4,hip-hop
51450,51450,68Dni7IE4VyPkTOH9mRWHr,J. Cole,2014 Forest Hills Drive,No Role Modelz,88,292799,True,0.690,0.521,...,-8.492,0,0.3390,0.324000,0.000000,0.0534,0.4940,100.028,4,hip-hop
51453,51453,3eekarcy7kvN4yt5ZFzltW,Travis Scott,HIGHEST IN THE ROOM,HIGHEST IN THE ROOM,82,175720,True,0.598,0.427,...,-8.764,0,0.0317,0.054600,0.000006,0.2100,0.0605,76.469,4,hip-hop
51458,51458,4C6Uex2ILwJi9sZXRdmqXp,Nicki Minaj,Super Freaky Girl,Super Freaky Girl,92,170977,True,0.950,0.891,...,-2.653,1,0.2410,0.064500,0.000018,0.3090,0.9120,133.010,4,hip-hop
51500,51500,7KXjTSCq5nL1LoYtL7XAwS,Kendrick Lamar,DAMN.,HUMBLE.,84,177000,True,0.908,0.621,...,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.4210,150.011,4,hip-hop
51501,51501,1rDQ4oMwGJI7B4tovsBOxc,Jack Harlow,First Class,First Class,86,173947,True,0.905,0.563,...,-6.135,1,0.1020,0.025400,0.000010,0.1130,0.3240,106.998,4,hip-hop
51503,51503,4woTEX1wYOTGDqNXuavlRC,Eminem;Dina Rae,The Eminem Show,Superman,86,350320,True,0.802,0.755,...,-3.138,0,0.0564,0.021500,0.000000,0.2950,0.5800,130.027,4,hip-hop
51504,51504,6gBFPUFcJLzWGx4lenP6h2,Travis Scott,Birds In The Trap Sing McKnight,goosebumps,84,243836,True,0.841,0.728,...,-3.370,1,0.0484,0.084700,0.000000,0.1490,0.4300,130.049,4,hip-hop
51507,51507,1r8ZCjfrQxoy2wVaBUbpwg,The Kid LAROI,Thousand Miles,Thousand Miles,81,164781,True,0.376,0.657,...,-4.658,1,0.0768,0.085800,0.000000,0.0884,0.2030,80.565,4,hip-hop
51600,51600,1fewSx2d5KIZ04wsooEBOz,Metro Boomin;Gunna,NOT ALL HEROES WEAR CAPES (Deluxe),Space Cadet (feat. Gunna),81,203266,True,0.901,0.464,...,-9.789,0,0.0645,0.368000,0.000017,0.2380,0.6380,109.004,4,hip-hop
51650,51650,0fX4oNGBWO3dSGUZcVdVV2,Kendrick Lamar,Mr. Morale & The Big Steppers,N95,83,195950,True,0.790,0.670,...,-5.527,1,0.1050,0.377000,0.000002,0.1190,0.4080,139.956,4,hip-hop
51651,51651,7AQim7LbvFVZJE3O8TYgf2,XXXTENTACION;Trippie Redd,17,Fuck Love (feat. Trippie Redd),83,146520,True,0.797,0.533,...,-9.740,0,0.0412,0.017200,0.000152,0.1030,0.3290,131.036,4,hip-hop
51652,51652,7iL6o9tox1zgHpKUfh9vuC,50 Cent,Get Rich Or Die Tryin',In Da Club,83,193466,True,0.899,0.713,...,-2.752,0,0.3660,0.255000,0.000000,0.0708,0.7770,90.051,4,hip-hop
51664,51664,2tTmW7RDtMQtBk7m2rYeSw,Bizarrap;Quevedo,"Quevedo: Bzrp Music Sessions, Vol. 52","Quevedo: Bzrp Music Sessions, Vol. 52",99,198937,False,0.621,0.782,...,-5.548,1,0.0440,0.012500,0.033000,0.2300,0.5500,128.033,4,hip-hop
51700,51700,40iJIUlhi6renaREYGeIDS,Drake;Travis Scott,Certified Lover Boy,Fair Trade (with Travis Scott),83,291175,True,0.666,0.465,...,-8.545,1,0.2600,0.050300,0.000000,0.2150,0.2920,167.937,4,hip-hop
51750,51750,2g6tReTlM2Akp41g0HaeXN,Kendrick Lamar;Blxst;Amanda Reifer,Mr. Morale & The Big Steppers,Die Hard,82,239026,True,0.775,0.736,...,-8.072,0,0.2470,0.319000,0.001160,0.1270,0.3620,100.988,4,hip-hop
51751,51751,59nOXPmaKlBfGMDeOVGrIK,Future;Drake;Tems,I NEVER LIKED YOU,WAIT FOR U (feat. Drake & Tems),89,189893,True,0.463,0.642,...,-4.474,1,0.3400,0.314000,0.000000,0.0686,0.3390,83.389,4,hip-hop
51752,51752,2xLMifQCjDGFmkHkpNLD9h,Travis Scott,ASTROWORLD,SICKO MODE,83,312820,True,0.834,0.730,...,-3.714,1,0.2220,0.005130,0.000000,0.1240,0.4460,155.008,4,hip-hop
51753,51753,7ycWLEP1GsNjVvcjawXz3z,A$AP Rocky;Skepta,TESTING,Praise The Lord (Da Shine) (feat. Skepta),82,205040,True,0.854,0.569,...,-8.151,0,0.1060,0.060900,0.081600,0.1000,0.2940,80.015,4,hip-hop
51761,51761,0Fs9cdPDhptWEDJmiCbkEW,J. Cole;Cults;Amber Coffman,Born Sinner (Deluxe Version),She Knows (feat. Amber Coffman & Cults),82,296520,True,0.766,0.740,...,-10.363,1,0.0807,0.019300,0.078400,0.2290,0.1830,118.008,4,hip-hop
51801,51801,503OTo2dSqe7qk76rgsbep,Dr. Dre;Snoop Dogg,2001,Still D.R.E.,84,270586,True,0.816,0.775,...,-3.323,1,0.2340,0.160000,0.000310,0.0543,0.5270,93.431,4,hip-hop

In [38]:
#movies.str.split('|').apply(lambda x: 'Action' in x)

<h1> How to add new coloumns

In [39]:
spotify['Platform']= 'Spotify'
#adds a new coloumn 'platform' with all values as 'spotify'

<h1> To change the data type of coloumns <h1>
<p> This method can be used to reduce the size of the dataset<p>

In [40]:
spotify.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   unique_id         114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
 21  Platform          114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(6)
memory usage: 18.4+ MB

In [41]:
spotify['key']=spotify['key'].astype('int32')

In [42]:
spotify['Platform']=spotify['Platform'].astype('category')

<h1> Important Functions <h1>

In [43]:
#value_counts() : no of times the data row has been repeated / no of times the row has been duplicated
spotify.value_counts()
spotify['artists'].value_counts()

artists
The Beatles                           279
George Jones                          271
Stevie Wonder                         236
Linkin Park                           224
Ella Fitzgerald                       222
                                     ...
Hillsong Worship;TAYA;David Ware        1
for KING & COUNTRY;Andy Mineo           1
Bethel Music;Francesca Battistelli      1
Descansa                                1
Jesus Culture                           1
Name: count, Length: 31437, dtype: int64

In [44]:
spotify.sort_values('danceability',ascending=False)
#ascending can also be as [True, False] for two or more coloumns
#In case of missing values, they are placed at the bottom of the table but can be brought to the first using
### spotify.sort_values('artists',na_position='first')
### spotify.sort_values('artists',na_position='last')
# we can also use inplace='True' to make the changes permanent

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform
111635,111635,4xKKIS9g9nivSiE7TtgR6V,Quantic,The Best of Quantic,Sol Clap,19,232853,False,0.985,0.65100,...,0,0.2170,0.00121,0.17600,0.064,0.405,115.347,4,trip-hop,Spotify
66576,66576,5kgT25LfYrXXMqNG2ia0O6,That Girl Lay Lay,Tha Cheat Code Reloaded,Medicaid Baby,10,199639,False,0.984,0.65000,...,1,0.0627,0.67400,0.00516,0.133,0.910,117.995,4,kids,Spotify
24916,24916,1viLe1wmYGwxIj5QOKOB5N,Delano Smith,An Odyssey,Inspiration,5,469240,False,0.983,0.56000,...,0,0.1350,0.00432,0.84100,0.101,0.762,124.980,4,detroit-techno,Spotify
73374,73374,0VomrCFhqYNVuhfIRPLeVa,Oliver Schories,Fields Without Fences,Daily Routines,49,412133,False,0.982,0.47800,...,0,0.2020,0.11800,0.74000,0.112,0.567,122.007,4,minimal-techno,Spotify
66793,66793,2g1EQO48cbVQy3YEGAe7rS,Mixx Master Lee,The Mississippi Cha Cha Slide A.K.A. STOMP 2007,"Featuring Mixx Master Lee, Red Rum & J. Smoov ...",7,341933,False,0.981,0.67500,...,1,0.0810,0.02910,0.00000,0.122,0.854,113.995,4,kids,Spotify
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113428,113428,5EYzrykQ95uOmepteDi9KT,El Ruido Blanco;Soñoliento Juan;Mantra para Do...,Aire Acondicionado de Ruido Blanco,Aire de verano,27,128000,False,0.000,0.18800,...,0,0.0000,0.13900,0.33900,0.122,0.000,0.000,0,world-music,Spotify
45729,45729,0pTAEdockvKVSq1hhFqk7O,Little Symphony,Rialto Beach,Amager,22,133624,False,0.000,0.00400,...,1,0.0000,0.97000,0.95900,0.109,0.000,0.000,0,guitar,Spotify
45720,45720,7i5OoyPXtSrqz9jobJfG1F,Little Symphony,Rialto Beach,Ritornello,23,102000,False,0.000,0.00129,...,1,0.0000,0.96900,0.95600,0.123,0.000,0.000,0,guitar,Spotify
101573,101573,7JiNqs52r97rOOjad76JhD,"Lightning, Thunder and Rain Storm;Thunderstorm...","Rain Drop Medley of Roof, Thunder, Forest, Car...",Heavier Rain Fall with Thunder,36,77121,False,0.000,0.40600,...,1,0.0000,0.00000,0.75700,0.357,0.000,0.000,0,sleep,Spotify
101569,101569,71JJl3lf8EqGs98hpd9k6B,Pink Noise,The Best Pink Noise,Pink Noise Relaxation,35,300001,False,0.000,0.00006,...,0,0.0000,0.12700,0.98500,0.237,0.000,0.000,0,sleep,Spotify

In [45]:
#ranking
spotify['popularity'].rank(ascending='false')

0         110449.0
1          92732.0
2          95723.5
3         109442.5
4         113290.5
            ...
113995     35349.5
113996     37698.5
113997     37698.5
113998     68324.5
113999     37698.5
Name: popularity, Length: 114000, dtype: float64

In [46]:
#works on series
spotify['popularity_rank']=spotify['popularity'].rank(ascending=False)

In [47]:
spotify

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5

In [48]:
spotify.sort_values('popularity_rank')

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
20001,20001,3nqQXoyQOWXiESFLlDF1hG,Sam Smith;Kim Petras,Unholy (feat. Kim Petras),Unholy (feat. Kim Petras),100,156943,False,0.714,0.472,...,0.0864,0.01300,0.000005,0.2660,0.238,131.121,4,dance,Spotify,1.5
81051,81051,3nqQXoyQOWXiESFLlDF1hG,Sam Smith;Kim Petras,Unholy (feat. Kim Petras),Unholy (feat. Kim Petras),100,156943,False,0.714,0.472,...,0.0864,0.01300,0.000005,0.2660,0.238,131.121,4,pop,Spotify,1.5
51664,51664,2tTmW7RDtMQtBk7m2rYeSw,Bizarrap;Quevedo,"Quevedo: Bzrp Music Sessions, Vol. 52","Quevedo: Bzrp Music Sessions, Vol. 52",99,198937,False,0.621,0.782,...,0.0440,0.01250,0.033000,0.2300,0.550,128.033,4,hip-hop,Spotify,3.0
30003,30003,4uUG5RXrOk84mYEfFvj3cK,David Guetta;Bebe Rexha,I'm Good (Blue),I'm Good (Blue),98,175238,True,0.561,0.965,...,0.0343,0.00383,0.000007,0.3710,0.304,128.040,4,edm,Spotify,7.0
20008,20008,4uUG5RXrOk84mYEfFvj3cK,David Guetta;Bebe Rexha,I'm Good (Blue),I'm Good (Blue),98,175238,True,0.561,0.965,...,0.0343,0.00383,0.000007,0.3710,0.304,128.040,4,dance,Spotify,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,28,5QAMZTM5cmLg3fHX9ZbTZi,Jason Mraz,Christmas Time,Winter Wonderland,0,131760,False,0.620,0.309,...,0.0495,0.78800,0.000000,0.1460,0.664,145.363,4,acoustic,Spotify,105990.5
27,27,0dzKBptH2P5j5a0MifBMwM,Jason Mraz,Feeling Good - Adult Pop Favorites,If It Kills Me,0,273653,False,0.633,0.429,...,0.0381,0.04440,0.000000,0.1320,0.520,143.793,4,acoustic,Spotify,105990.5
26,26,5IfCZDRXZrqZSm8AwE44PG,Jason Mraz,Holly Jolly Christmas,Winter Wonderland,0,131760,False,0.620,0.309,...,0.0495,0.78800,0.000000,0.1460,0.664,145.363,4,acoustic,Spotify,105990.5
24,24,3Hn3LfhrQOaKihdCibJsTs,Jason Mraz,Human - Best Adult Pop Tunes,Unlonely,0,231266,False,0.796,0.667,...,0.0392,0.38100,0.000000,0.2210,0.754,97.988,4,acoustic,Spotify,105990.5
23,23,0BUuuEvNa5T4lMaewyiudB,Jason Mraz,Coffee Moment,93 Million Miles,0,216386,False,0.572,0.454,...,0.0258,0.47700,0.000014,0.0974,0.515,140.182,4,acoustic,Spotify,105990.5

In [49]:
#sort_index: (For both series and dataframes)
spotify.sort_index(ascending=False)

,Unnamed: 0,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0

In [50]:
#to rename columns
spotify.rename(columns={'Unnamed: 0':'Serial No.'},inplace=True)
spotify.set_index('Serial No.',inplace=True)

In [51]:
#to rename index
spotify.rename(index={'First':0},inplace=True)

In [52]:
spotify.reset_index()
#for permanent changes use inplace(True)

,Serial No.,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5

In [53]:
#Replacing existing indexing without loosing other columns
spotify.reset_index().set_index('Serial No.')
### Note the output of reset index to series is a dataframe

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5

In [54]:
#unique number of data (used only for series)
### Will count missing values
print(spotify['artists'].unique())
len(spotify['artists'].unique())

['Gen Hoshino' 'Ben Woodward' 'Ingrid Michaelson;ZAYN' ...
 'Cuencos Tibetanos Sonidos Relajantes'
 'Bryan & Katie Torwalt;Brock Human' 'Jesus Culture']

31438

In [55]:
spotify['artists'].nunique()
### Will not count missing values

31437

In [56]:
#isnull (series and DataFrame); if null value then true else false
spotify.isnull()

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,,
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [57]:
#notnull (series and DataFrame); if null value then False else True
spotify.notnull()

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,,
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
113996,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
113997,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
113998,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
113999,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [58]:
#True if there is any Null value in a series and False if there is no null value in the series(ONLY FOR SERIES NOT FOR DATAFRAMES)
spotify['artists'].hasnans

True

In [59]:
spotify.dropna()# spotify.dropna(how='any') ->removes all rows even if there is one null value (both series and dataframes)
spotify.dropna(how='all') #removes the rows in which all values are null
spotify.dropna(subset='artists') #removes the row if any null values found in 'artists'; can also add multiple columns using ','

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5

In [60]:
spotify['artists'].fillna('unknown') #Replaces the null values in series or dataframe with 'unknown'

Serial No.
0                    Gen Hoshino
1                   Ben Woodward
2         Ingrid Michaelson;ZAYN
3                   Kina Grannis
4               Chord Overstreet
                   ...
113995             Rainy Lullaby
113996             Rainy Lullaby
113997             Cesária Evora
113998          Michael W. Smith
113999             Cesária Evora
Name: artists, Length: 114000, dtype: object

In [61]:
spotify['energy'].fillna(spotify['energy'].mean) #replacing the missing values with mean of other values

Serial No.
0         0.4610
1         0.1660
2         0.3590
3         0.0596
4         0.4430
           ...
113995    0.2350
113996    0.1170
113997    0.3290
113998    0.5060
113999    0.4870
Name: energy, Length: 114000, dtype: float64

In [62]:
spotify.fillna(method='ffill')#replaces null with previous values
spotify.fillna(method='bfill')#replaces null with next value

/tmp/ipykernel_10485/742032541.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  spotify.fillna(method='ffill')#replaces null with previous values
/tmp/ipykernel_10485/742032541.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  spotify.fillna(method='bfill')#replaces null with next value

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5

In [63]:
spotify.duplicated().sum()

np.int64(450)

In [64]:
spotify.drop_duplicates()
#spotify.drop_duplicates(keep='first') ->Will keep the first and remove other
#spotify.drop_duplicates(keep='last') ->VIce versa

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Spotify,3552.0
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Spotify,21269.0
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Spotify,18277.5
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Spotify,4558.5
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Spotify,78651.5
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Spotify,76302.5
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Spotify,76302.5
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Spotify,45676.5
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Spotify,76302.5

In [65]:
#find the last match played by virat kohli

In [66]:
#drop (series and dataframe): to drop columns or rows
spotify.drop(columns=['speechiness','liveness'])
#spotify.drop(index=[1,2]) -> will drop rows, can also set index to some other column and delete using that index value

,unique_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,acousticness,instrumentalness,valence,tempo,time_signature,track_genre,Platform,popularity_rank
Serial No.,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.0322,0.000001,0.7150,87.917,4,acoustic,Spotify,3552.0
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.9240,0.000006,0.2670,77.489,4,acoustic,Spotify,21269.0
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.2100,0.000000,0.1200,76.332,4,acoustic,Spotify,18277.5
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.9050,0.000071,0.1430,181.740,3,acoustic,Spotify,4558.5
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.4690,0.000000,0.1670,119.949,4,acoustic,Spotify,710.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.6400,0.928000,0.0339,125.995,5,world-music,Spotify,78651.5
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.9940,0.976000,0.0350,85.239,4,world-music,Spotify,76302.5
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.8670,0.000000,0.7430,132.378,4,world-music,Spotify,76302.5
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.3810,0.000000,0.4130,135.960,4,world-music,Spotify,45676.5
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.6810,0.000000,0.7080,79.198,4,world-music,Spotify,76302.5

In [67]:
#apply(series and dataframe): to perform calculations on columns
points=[[(1,2),(2,3)],[(1,2),(3,3)],[(1,2),(4,3)]]
pts=pd.DataFrame(points,columns=['Point A', 'Point B'])
pts

  Point A Point B
0  (1, 2)  (2, 3)
1  (1, 2)  (3, 3)
2  (1, 2)  (4, 3)

In [68]:
def dist(pts):
  A=pts['Point A']
  B=pts['Point B']
  return ((A[0]-B[0])**2+(A[1]-B[1])**2)**0.5

In [69]:
pts['Distance']=pts.apply(dist,axis=1)

In [70]:
pts

  Point A Point B  Distance
0  (1, 2)  (2, 3)  1.414214
1  (1, 2)  (3, 3)  2.236068
2  (1, 2)  (4, 3)  3.162278

In [71]:
#Session 19
#Session 20
#Session 21
#Session 22